### ISSUE TITLE
Reordered sequential navigation

### ISSUE THREAD

**Issue by frivoal** [WICG/spatial-navigation#10]
There is a recurrent complain coming form a11y people that sequential navigation (aka moving focus with the tab key) as it is today is not adequate for all use cases / all users, especially in the face of increasingly powerful tools in CSS to lay things out with relatively little connection with the document order.

This has led to suggestions that sequential navigation should follow the `order` property in flexbox, or that it should follow "the visual order", or to the suggestion that there should be a `nav-index` property, or that there should be a `nav-next` property, or a `nav-order` property, or a combination of the previous things with some mechanism to scope it to a DOM sub-tree.

There are multiple difficulties with that:

* While the DOM tree has a natural order, a visually laid out document does not. It is in 2D, which has no inherent ordering, and on top of this color, contrast, size, movement, and more come to influence in what order things are typically perceived. This makes it far from trivial in the general case to find a linear order which could be described as "the visual order". This makes it neither easy to define an order the browser should go through, nor to find the right set of properties that authors could use to express it.

* There seem to be multiple overlapping and conflicting requirements. Sighted mouse users who occasionally use the keyboard as a supplemental navigation aid expect different things form sighted people who primarily navigate by the keyboard, who in turn expect different things from blind or partially blind users who primarily navigate the document based on its logical structure.

Discussions in the CSS-WG and in the WICG meeting leading to the creation of this repo have generally agreed that at least some of the cases that had previously been expressed as a desire for reordered sequential navigation would probably be better server by spatial navigation. The general consensus is that a good way forward is to first focus on getting spatial navigation to work, then look for use cases that are still not adequately covered by the combination of (non-reordered) sequential navigation and spatial navigation.

To be most useful, such use cases should document:
1. How the document is marked up
2. How the document is laid out
3. What class of users or what usage scenario is still not well served neither by sequential navigation nor by spatial navigation.

I have created a [wiki page to document these use cases](https://github.com/WICG/spatial-navigation/wiki/Use-cases-for-reordering-sequential-navigation). Contributions most welcome.

Also, since this has been a long running topic, linking to (and summarizing) previous conversations would probably be useful. There's a [wiki page for that](https://github.com/WICG/spatial-navigation/wiki/Historical-discussions-of-reordering-sequential-navigation) too.

I would like to encourage people interested in this issue in contributing to the two wiki pages above. With that information, and once we've made enough progress on spatial navigation (See the rest of this repository for this broader topic), it will be much easier to return to this topic and see what is left to solve.

**Comment by Nadya678** [comment]
Any equivalent for focusing the HTML object and/or to make it tabbable is needed. I use in many html5 projects `tabindex="-1"` on span to make the element focusable by mouse/touch and `tabindex="0"` to make te element tabbable. There are specialized controls made from `<span/>, <input/>` and `<label/>` elements. Part of these projects are commercial and they validate on W3C.org including html5 and css3. 

Because users (my clients) need select/option field fully styled (including dropdown arrow and list), I also made <select/> equivalent with use of `<span/>, <input/>` and `<label/>` elements. The dropdown works via :focus on span (tabindex="-1"). There is no tab-index="0" because the used <input type="radio"/> are tabbable. This control works with touch/mouse and keyboard without any JS. 

I read the attribute "tabindex" will be removed from html5 (probably without changing DOCTYPE declaration- why?) It is in use.

In new specification **(if tabindex will be removed - WITHOUT DEPRECATION - YES, tabindex is not deprecated now**), there is needed new CSS attribute.

Because in CSS is possible absolute positioning and fixed positioning, there will be needed also positive values of tab-index/nav-index according to  w3c/csswg-drafts#1748. Probably also nav-group due to discussions. Other proposed solution for the problem (in other threads)  are often buggy for absolute-positioned elements and for fixed positioned elements. 

There is also needed "nav-index: none;" if a "modal" "window" (a `<section/>, <aside/>, <form/>` or `</div>` only looking like dialog window) will be shown for example with any form. 
`user-select:none;` still lock only clicks but no keyboard navigation. There is many questions on stack overflow to this problem. Not solved. I patially solved this problem for radio+label and checkbox+label fields and for `<a><span/></a>` sequecce with manipulation of visibility but no solution for TextBox and `<textarea/>`. The solution is hard but shall be easy to use... 

**BTW: my clients won't understand, the `<select/>` cannot be fully styled and they needs... solution for this problem with change ONLY FRONT-END. If html5 attribute tabindex for `<span/>` will be removed, I have no solution for them for the moment.**

**Comment by SebastianZ** [comment]
@Nadya678 I'm not sure where you read that the `tabindex` HTML attribute would be deprecated. `tabindex` can't be removed, because that would break the Web.

What was discussed in the threads linked here was a possible `nav-index` CSS property _in addition_ to the HTML attribute `tabindex`.

Sebastian

**Comment by patrickhlauke** [comment]
for avoidance of doubt, worth noting: the problem is not just about focusable elements (moving focus with the tab key). this also affects overall reading order when using assistive technologies (e.g. using a screen reader, using reading keys to consumer the content of the document). not something that can just be patched with tabindex or whatever, but rather a fundamental problem of how the content is exposed in a linear fashion to AT.

**Comment by frivoal** [comment]
Issue migrated to w3c/csswg-drafts#3377
