### ISSUE TITLE
Can i use Polyfill | spatial-navigation free in commercial use?

### ISSUE THREAD

**Issue by elmer120** [WICG/spatial-navigation#134]

**Comment by jihyerish** [comment]
Hi, the polyfill is under the MIT License. 
(https://github.com/WICG/spatial-navigation/blob/master/polyfill/LICENSE)

Yes, you can use it for the commercial use. [Here](https://tldrlegal.com/license/mit-license) is the detail about the MIT License.
I recommend you to use the [released version](https://www.npmjs.com/package/spatial-navigation-polyfill), because the polyfill in the github is unstable.

**Comment by elmer120** [comment]
Thanks so much!!
