### ISSUE TITLE
Is using the enter key the right approach?

### ISSUE THREAD

**Issue by frivoal** [WICG/spatial-navigation#15]
When focusable elements are nested, the inner one is neither to the top, bottom, left, or right of the outer one (typically, though it can with overflowing layouts).

This is particularly common when there are focusable things inside a scroller, since scrollers themselves are focusable.

The spec proposes to use the enter key to "navigate inside". This is introduced in the https://wicg.github.io/spatial-navigation/#overview section, and futher detailed in file:///Users/florian/src/spatial-navigation/index.html#processing-model.

Is this the best approach? I think so, but this is worth discussing. Here are a few arguments as to why this was specified the way it is:

* Just relying on the `tab` key isn't good enough, since not all spatial input devices have a `tab` key (remote controls, gamepads, etc)

* legacy implementations of spatial navigation have coped decently without this feature because much legacy content was crafted specifically for TV, and used very simple layouts where the situation does not arise. Making spatnav a feature of the general web means we need to make sure it is resilient to a broader range of situations, so we need something

* The enter key is a "natural" answer to this question, and is always available on any spatnav capable input device (otherwise it couldn't click).

* The enter key does not have pre-existing behavior of scrollable areas, so this addition does not conflict with anything

* A possible alternative would be that:
    1. when the focus would normally move to a scroller, we first check if it has visible focusable descendants, and automatically focus one of the descendants rather than the scroller if there are any.
    2. If a scroller is focused (maybe because no focusable descendant was visible, or maybe because we decided against implementing i), and there are visible focusable descendant the the next directional navigation would focus one of them instead of scrolling.

    This solution would also work, but it felt harder to understand for users: some scrollers can be focused, some cannot, and it may not be immediately clear why. Also, this makes it hard for a user to skip past a scroller, since its content would be directly focused. With the enter-key approach, whether to dive into an element or skip over it is the users's choice.

    That said, it is a possible consideration. Note that the root is effectively special-cased to use this logic, as the downsides mentioned above do not apply to that case, and having to press enter to get to anything at all in the page would be silly.

**Comment by bkardell** [comment]
I had a similar thought when reading the spec fwiw.. I'm not sure enter is excellent, iirc from our conversation at tpac one of the people had thoughts on this, though I can't recall who :(

**Comment by anawhj** [comment]
I agree that we could extend the default behaviors of `enter` key for the spatial navigation. In the browser, there have been several original default behaviors of `enter` key such as a selection of `<button>` (technically speaking, click event trigger), CRLF of `<textarea>`.

We could just add an additional default behavior of `enter` key for the container element of spatial navigation, so that we can move the focus to an element in upper left corner of the container element. In this situation, the container element can be classified as a document element, a scrollable region, and a non-scrollable region with `spatnav-container='create'` (though the naming of property and its value hasn't been fixed yet.)

For reference, the document element and scrollable region are defined as a focusable area in [html spec](https://html.spec.whatwg.org/multipage/interaction.html#data-model), while I'm sure that it's no way to move the focus to a nested element of the container element only using `arrow` keys(LRUD) for now.

On the other hand, we would consider a way how to delegate the focus from a container to its nested element so that the container just delivers the focus to one of its descendants at once when it gets focus. It seems easy to handle it using some existing JS API plus new event types specified in [SpatNav ](https://wicg.github.io/spatial-navigation/#events-navigationevent)spec.

**Comment by frivoal** [comment]
> We could just add an additional default behavior of enter key for the container element of spatial navigation, so that we can move the focus to an element in upper left corner

This is effectively what the SpatNav specification currently does.

> I'm sure that it's no way to move the focus to a nested element of the container element only using arrow keys(LRUD) for now.

Yes. With the specification as it is now, the ENTER key is necessary to move to nested elements. LRUD only cannot do it.

> On the other hand, we would consider a way how to delegate the focus from a container to its nested element so that the container just delivers the focus to one of its descendants at once when it gets focus. It seems easy to handle it using some existing JS API plus new event types specified in SpatNav spec.

Yes. If we want to keep the specification as it is, authors can do it in javascript

```javascript
/* when focusing an element, check if it is a scroller
and if so, move the focus inside it if it has focusable descendants. */
document.addEventListener("navbeforefocus", function(e) {
  if (getComputedStyle(e.relatedTarget).overflow == "visible") return; /*not a scroller */

  var c = e.relatedTarget.findSpatNavCandidates( {
    dir: "inside", container: e.relatedTarget });
																				 
  if (!c) return; /* no visible focusable descendant */

  e.preventDefault();
	
  var best = e.relatedTarget.selectSpatNavBestCandidate({
    dir: "inside", candidates: c });
  best.focus();
});

/* when scrolling an element, check if it is a scroller
move the focus inside it if it has focusable descendants. */
/*.. something similar to the previous function, but based on navbeforescroll..*/
```

Note that the opposite is true as well: if we switch the specification to the mode where focusing descendants of scroll containers happened by default, authors could easily use javascript to switch to the opposite behavior.

**Comment by frivoal** [comment]
@bkardell Right, I am not sure which one is better. The ideal way answer this question is to implement both, and run a usability study asking users to try both systems on lots of web pages and see which one they find easier to use.

Without doing that, it is a subjective call...

The currently specified behavior offers more control, because users can descide whether they want to enter a scrollable area (press enter), ok skip over it (keep using the arrows). But it may be less discoverable, as you cannot reach all the elements in the page if you don't know about the enter key.

If we switch to automatically focusing descendants of scroll containers, the specification would be a little bit simplified, as we would no longer need the "inside" direction of navigation, and could remove special handling of the root.

Either way, authors can switch from one behavior to the other if they want to using javascript as discussed in the previous comment, and we could also make (in level 2) a css property that let's you switch between the two. But that doesn't really help us chose which is the best.

I am a little bit tempted to switch to automatically focusing children.

Upsides:
* It would simplify the specification
* That's how Chrome and Presto implement spatnav currently
* users need to learn fewer keys to keys
* Jihye & Brad seem to like that behavior better

Downsides:
* Users have to go through the nested content, and cannot easily skip over scrollers
* I think I like the behavior with the ENTER key better

Either way:
* Authors can flip the behavior using JS

**Comment by frivoal** [comment]
If people think it's a good idea, I am happy to write a pull request to change switch models.

**Comment by hugoholgersson** [comment]
> ...some scrollers can be focused, some cannot, and it may not be immediately clear why.

If you go for "autofocusing children", please consider [crbug.com/801162](https://crbug.com/801162), i.e please ensure that also overflow scrollers _without_ focusables never loose their scrollability. I outlined a potential solution in [a design doc](https://bit.ly/snav2). What do you think about it?

Personally, as a _user_, I do like the ENTER-approach. I think it allows for faster navigation. On TVs etc, we could also make use of the BACK-button... (= move focus back to the element that had focus before entering the scroller)... However,  I can really imagine it, at first, not being as intuitive as only using the arrow-keys.

**Comment by jihyerish** [comment]
> If you go for "autofocusing children", please consider crbug.com/801162, i.e please ensure that also overflow scrollers without focusables never loose their scrollability. I outlined a potential solution in a design doc. What do you think about it?

I agree with your idea:

- Allow spatnav (and TAB-navigation) to focus scrollable areas i.e. treat scrollable areas as divs with tabindex=0
- Allow spatnav to scroll a focused scrollable area.

But, not sure about using the enter key.

- It may confuse the existing behavior of the enter key which is used to submit something.
- I want to make sure the arrow key can navigate all the elements.
There are some devices which don't have the enter key, but use the spatial navigation.
Using the BACK-button for entering the container doesn't seem natural to me.
- If we have the enter key for entering, some users may be curious about the key for escaping the container.

We can also use the arrow key instead of the enter key for entering the container if it gains the focus.
If we can do this, the arrow key shouldn't work for scrolling and entering at the same time.
