### ISSUE TITLE
API for finding the next focusable element

### ISSUE THREAD

**Issue by jihyerish** [WICG/spatial-navigation#2]
The JS API for finding the next focusable element would be useful.
```javascript
element.nextFocusableElement(optional focusNavigationOptions options)
```
It returns the next focusable element or the list of the focusable elements.
By using it, we can predict the focus event and prepare for it.
It can be used with the focus looping, for example, disabling the focus looping if there isn't the next focusable element.

The IDL would be: 

```javascript
element.nextFocusableElement(optional focusNavigationOptions options)

dictionary focusNavigationOptions {
  FocusNavigationRule rule = "nearest";
  NavigationDirection direction;   // Is this necessary? If it does, what will be the default?
}

enum FocusNavigationRule { "direction", "projection", "nearest" }
enum NavigationDirection  { "up", "down", "left", "right" }
```

- If `direction` is omitted, the API returns the list of focusable element in 4 directions.

**Comment by frivoal** [comment]
I think this is useful, and it could potentially replaced the `focusUp()` etc API proposed in https://github.com/lgeweb/spatial-navigation/issues/7, as you could do
```javascript
elm.nextFocusableElement({direction="up"}).focus();
```
instead of 
```javascript
elm.focusUp()
```
However, for the first iteration, I would probably not include the `rule` parameter, for the reasons discussed in https://github.com/lgeweb/spatial-navigation/issues/6: that is hard to get right, and providing an API to let authors to it themselves seems safer at first.

As discussed in https://github.com/lgeweb/spatial-navigation/issues/7, I would probably also support `next` and `previous` as possible values for `direction` in addition to `up` `down` `right` and `left.

However, I'd probably keep this API to only returning a single element, not a list.

**Comment by hugoholgersson** [comment]
I also think that a JS API is better than CSS properties. 

A rule-parameter would be very useful - but hard to implement. Current heuristics in chromium only has one "best effort" mode... Authors have no way to know where it wants to go next - but this JS API would let them know that.

> As discussed in #7, I would probably also support next and previous as possible values for direction in addition to up down right and `left.

Makes sense! That would let authors know where TAB-key navigation wants to go too.

Question: Why not `document.nextFocusableElement()`? (The next focusable element will depend the `document`'s `activeElement` anyway?).

**Comment by jihyerish** [comment]
> Question: Why not document.nextFocusableElement()? (The next focusable element will depend the document's activeElement anyway?).

It makes sense when the spatial navigation is applied to the whole document.
But we are also considering to apply the spatial navigation to the group of elements.
On this case, element.nextFocusableElement() is suitable.

**Comment by frivoal** [comment]
Bikesheding asside, during the [discussion in the WICG meeting at TPAC 2017](https://www.w3.org/2017/11/09-wicg-minutes.html) we had a growing consensus that an API like this one was probably the right way to go:
* Can be called on arbitrary elements
* Take a parameter for the direction
* Returns the element that the browser would move the focus to if navigation in that direction was attempted
* initial set of directions should be "up" "down" "right" "left", and maybe also "next" and "previous", but with a syntax that could be extended later with more keywords (for 8-way nav, or for "inside" and "outside"), or with angles.

We also seemed to agree that a corresponding even should exist: called when the user's action would cause the browser to invoke spatial navigation (and also sequential nav if we include "previous" and "next"), so that js could intercept, potentially calling `preventDefault()` and picking an alternative target by calling `focus()` on it.

We were short on time, so the discussion did not fully conclude, but that seemed to be what we were converging on at the time, both as a standalone usefull thing, and as a building block for polyfilling more advanced spatnav features.

Next up: if someone disagrees with the above, they should say so, otherwise, we should try and make a first draft attempt at specifying that.

**Comment by frivoal** [comment]
It was also mentioned that https://www.w3.org/TR/2015/WD-indie-ui-events-20150115/#UIFocusRequestEvent is probably a good thing to read, as it attempted to solve a similar problem.

**Comment by frivoal** [comment]
Solved by https://wicg.github.io/spatial-navigation/#js-api

Feel free to open new issues if there's anything wrong with that API, but "there should be an API" is considered done.

**Comment by FbN** [comment]
> Solved by https://wicg.github.io/spatial-navigation/#js-api
> 
> Feel free to open new issues if there's anything wrong with that API, but "there should be an API" is considered done.

Is not the api missing the the "next" and "previous" direction? How to simulate TAB next element focus with Navigation Spatial API without a 'next' direction?

**Comment by jihyerish** [comment]
@FbN , am I understanding right that you're referring window.navigate() API?
For Spatial navigation, we don't consider sequential navigation, which is navigating with TAB.
Do you have some use cases for this API with the next/previous direction?
