### ISSUE TITLE
Scrolling propagation

### ISSUE THREAD

**Issue by frivoal** [WICG/spatial-navigation#26]
The propagation of scrolling up the ancestor chain described in the spec (for the non spatnav case) is how Chrome and Safari behave, but Firefox is different. We should get the spec and all implementations to align.

Note: this may interact with https://github.com/WICG/spatial-navigation/issues/19

**Comment by hugoholgersson** [comment]
Is this the same problem as http://crbug.com/585413 ?

I'd like the spatnav algorithm to behave more lite I've outlined in http://bit.ly/snav2 = instead of propagating scroll-actions outside fully scrolled scrollers, we first focus that scroller.

Firefox's Tab-key navigation does this. I believe spatnav (aka directional navigation) and tab-key navigation (aka sequential navigation) should handle scrollers in the same way.

**Comment by frivoal** [comment]
closed by https://github.com/WICG/spatial-navigation/commit/27cdd49d71f69022eb921d1b9301acd2e36de66e
