### ISSUE TITLE
The CSS at-rule for enabling the spatial navigation

### ISSUE THREAD

**Issue by jihyerish** [WICG/spatial-navigation#3]
There is another possibility to enable the spatial navigation, using CSS at-rule.
Such as` @navigation`, it lets you define the way to move the focus in 4 directions (up/down/left/right).

`@navigation` can have a set of descriptors like:

- `mode: always | common | only`
  - How the spatial navigation works.
  - always: The spatial focus navigation always works in preference to control UI (such as controlling the scrollbar).
  - common: The spatial focus navigation works, but controlling UI takes the higher priority than that.
  - only: The spatial focus navigation works with ignoring the UI controls.
    - This seems risky for the compatibility issue.
- `target: <id> | <class> | root`
  - Where the spatial navigation is applied.
- `keys: <string>` (or something means the keycode)
  - Which triggers the spatial navigation. This matches with the keycode, so the specified key will work for the input of the spatial navigation.

For example, 

```css
@navigation myNavigation{
  mode: common;
  keys: 0x26 0x28 0x25 0x27;
}
 
#sub_root {
   nav-rule: myNavigation;
}
```
This means that the spatial focus navigation works, but controlling UI takes the higher priority than that, and the input is arrow keys.

**Comment by jihyerish** [comment]
The keyCode values of each browser's keydown event are known in the standard position like:
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode#Browser_compatibility.

**Comment by frivoal** [comment]
I think we need to be a bit more specific about what "enabling spatial navigation mode" means. In my mind, UAs should always be free to have spatnav off or on by default, and if it's on, they should be able to pick if it is tied to the arrow keys (typical for a TV remote which cannot really do anything else), or to some other key combination like shift+arrow (typical for a desktop) to avoid interfering with user expectations or with event handlers in the page.

In that context, "enabling spatial navigation" is a way for the page author to tell the browser that the page is designed in such a way that having spatnav turned on using arrow keys is safe on this page as there is no navigation or script that expects otherwise.

With that in mind:

> keys: <string>

I am not sure what the use case for this is. Why would an author want to activate spatial navigation on keys other than arrow keys?

I think it can be reasonable for UAs to offer spatnav on some other key combination such as SHIFT+[ARROW], especially if the UA turns then on by default, but for a page author, the only thing that seems useful to me is to let the UA know that spatnav on arrow keys is fine.

Maybe a good first step here would be to add a Javascript API to invoke spatial navigation, (something like `elm.focusUp()`, `elm.focusLeft()` etc, and maybe a `elm.focusNext()` while we're at it). Then authors can trigger spatial navigation on any key they want, or on mouse events, gestures, etc. If it turns out that authors often want to map spatial navigation to keys other than arrow keys, then we can later add a declarative shortcut for that.

I just filed a [separate issue](https://github.com/lgeweb/spatial-navigation/issues/7) to discuss that API separately.

> mode: always | common | only

Can you explain the difference between `always` and `only`?

As for `always` / `only` vs `common`, if I understand correctly, the question is what should happen if you press down on a focused element that can scroll down: scroll or move to the next element? maybe it should make a difference whether the element is already scrolled to the bottom or not? Also, what should happen if the focused element is an editable one, where the arrow keys normally control the caret.

I would like to understand the behavior of existing UAs that have arrow keys as spatial navigation on by default to see how they solve this problem, to help me understand better what use cases need changing that default. Also, if they do not all have the same default, this is something we may need to work on standardizing as well.

If I understand correctly, `common` would be something like this:
When a scroller is focused pressing an arrow key in the scrollable direction should scroll, and if we reach the end of the scroller we activate spatnav in that direction (which sounds like `common`). If the author doesn't want that and would like spatnav to activate even if it would be possible to scroll, maybe they could use prevent default in a key event handler and invoke the `focusDown()` method. Something similar seems possible for editable elements: if the caret is on the top line and arrow up is pressed, focus up. If it is at the bottom line and arrow down is pressed, navigate down, etc, otherwise move the caret.

Another possibility I guess would be that arrow keys would always trigger spatnav, but if you were on an scrollable element, you could press enter to enter scroll mode, and escape to go back to navigation mode (or something like that). Same thing with editable controls: press enter to edit, escape to go back to focus/navigation. I wonder if some existing UAs or sites using polyfils behave like that.

**Comment by jihyerish** [comment]
> With that in mind:
> 
>> keys:
>
> I am not sure what the use case for this is. Why would an author want to activate spatial navigation on keys other than arrow keys?

In the gamepad or the game emulator use the other keys for the directional navigation.
Or someone who doesn't want to use the arrow keys for both controlling UI and the spatial navigation can use those features in separate keys.   (like the presto based opera used the arrow keys with shift key for the spatial navigation). 
But this is a brief idea, and this isn't mandatory feature, so the `keys` descriptor can be dropped for now.
I also think that the proposed API should support the key feature for the spatial focus navigation.

>> mode: always | common | only
>
> Can you explain the difference between always and only?

- `always`: both spatial navigation and controlling UI (e.g., scrolling down the scroll bar) works, but focus navigation works first.
- `only`: arrow keys just work for the spatial focus navigation and the origin behavior of them (controlling UI ) is ignored.
`only` is bit unnecessary and it can cause compatibility issues so that it can be dropped.

I assume that the scrollable area cannot be focusable.
But the focus can move to the element in the scrollable area.

The behaviors of `always` and `common` are like this:
For example, beneath the currently focused element, there is a scrollable area.
Let there is a focusable element in the scrollable area, and its top edge is under the bottom edge of the scrollable area. (entirely out of the view)

When the arrow down key is pressed, 
- if `always` is applied, the scrollable area scrolls down automatically until the focusable element is entirely in the view and focus moves to the element.
- otherwise `common` is applied, the user can scroll down the scrollable area with the down arrow key until the focusable element is entirely in the view, and then focus moves to the element.

**Comment by frivoal** [comment]
I think I understand now, thank you.

Overall, I believe I prefer `arrow-key-behavior` as a way to activate spatial navigation (preferably turned into an at-rule).

We still need to define the precise processing model, so that the interaction between scroll, spatnav and events is wel  defined and manageable, but that seems a separate topic.

**Comment by jihyerish** [comment]
I guess there are some differences between @navigation and @arrow-key-behavior (in #5): 

- Coverage of the at-rule
  - `@navigation` can be applied to the element
  - `@arrow-key-behavior` is applied to the document
- Descriptors of the at-rule
  - `@navigation` has extra `target` and `keys`

I think enabling the spatial navigation should be applied to the whole page, and using it only to the group of elements is unnecessary.
But, we the navigation rule could be applied to the different groups of the elements on the same page. For example, some web pages consist of groups based on their functions or behaviors (e.g., main, menu, dialog, etc.). This need to be discussed in a separate issue.

Therefore, if the at-rule can only activate spatial navigation and not support the navigation rule,
I agree with you.

> We still need to define the precise processing model, so that the interaction between scroll, spatnav and events is wel defined and manageable, but that seems a separate topic.

Indeed. It's the most important and tricky part of the spatial navigation.

**Comment by frivoal** [comment]
During the [discussion in the WICG meeting at TPAC 2017](https://www.w3.org/2017/11/09-wicg-minutes.html), it was brought up that "enabling" spatial navigation, in addition to being useful at the page level, was also something people would likely want to do on a component basis.

This means that instead of targetting the document, the mechanism for enabling spatial navigation needs to be a thing that targets an element / subtree. If this is to be in css, that means a property instead of an at-rule.

**Comment by frivoal** [comment]
Alternatively, maybe it shouldn't be on aritrary elements/ subtrees, and could be coupled with the shadow dom.

**Comment by frivoal** [comment]
This is solved by https://wicg.github.io/spatial-navigation/#activation

Feel free to open new issues if there's anything wrong with that property, but "there should be an way to turn spatnav on" is considered done.
