### ISSUE TITLE
Add a container-field to NavigationEvent

### ISSUE THREAD

**Issue by hugoholgersson** [WICG/spatial-navigation#33]
Let's add a `container`-attribute to `NavigationEvent`?

It will default to document.body unless `spatnav-container` imposed a restriction on the search.

When dispatching the event, the browser has this information at hand already, so why not share this possibly important piece of information to authors?

**Comment by frivoal** [comment]
In `navnotarget` and `navbeforescroll`※ it is included already in `relatedTarget`.

What would you suggest we put in `relatedTarget` for `navnotarget` and `navbeforescroll` if there was a separate `container` attribute? The same information? `null`?

※ In the case of `navbeforescroll`, `relatedTarget` is described as the thing you scroll, but that's a spatnav container anyway, so it's just a matter of how you look at it. The info is there.

> It will default to document.body unless spatnav-container imposed a restriction on the search.

Or unless there's a scroller in the ancestry chain, since this create spatnav containers as well.

**Comment by hugoholgersson** [comment]
I didn't think of that. But I realized, I think `nextFocus` is a better name than `relatedTarget`, see  #34.

> What would you suggest we put in relatedTarget for navnotarget and navbeforescroll if there was a separate container attribute? The same information? null?

Yes, maybe `null` is fine? That's a hint that nothing will be focused?

> > It will default to document.body unless spatnav-container imposed a restriction on the search.
> Or unless there's a scroller in the ancestry chain, since this create spatnav containers as well.

Right. Good point. Scrollers that "jail" the focused element would be reported in `container` as well. Chromium's current spatnav algorithm happily exits scrollers, so today scrollers don't impose any restrictions. This is something I'd like to see [fixed by first focusing the scroller](http://bit.ly/snav2).

**Comment by hugoholgersson** [comment]
Finding the parent scroller, i.e. the element's "container", can be done in standard JS [[1](https://gist.github.com/twxia/bb20843c495a49644be6ea3804c0d775)] [[2](https://developer.mozilla.org/en-US/docs/Web/API/Node/contains)].
