### ISSUE TITLE
Rename relatedTarget to something like nextFocus?

### ISSUE THREAD

**Issue by hugoholgersson** [WICG/spatial-navigation#34]
DOM [Events](https://dom.spec.whatwg.org/#event) already have two attributes that are named \*target\*; `currentTarget` and `target`.

Let's not add a third one? To me, and maybe to others who are not fluent in JavaScript, this is a bit confusing.

Readers shouldn't need to go check the spec to get an idea of what the code does.

**Comment by frivoal** [comment]
`relatedTarget` is actually also [introduced by DOM](https://dom.spec.whatwg.org/#event-relatedtarget), which does not give it any particular semantic, but does define how it should be handled so that the right thing happens when crossing shadow DOM boundaries.

So, `relatedTarget` is what various UI-Events use as an attribute name when they need something like this. Examples (in some of these, it is set to `null`):
* [FocusEvent](https://w3c.github.io/uievents/#idl-focusevent) events, including [blur](https://w3c.github.io/uievents/#event-type-blur), [focus](https://w3c.github.io/uievents/#event-type-focus), [focusin](https://w3c.github.io/uievents/#event-type-focusin), [focusout](https://w3c.github.io/uievents/#event-type-focusout), [DOMFocusIn](https://w3c.github.io/uievents/#event-type-DOMFocusIn), and [DOMFocusOut](https://w3c.github.io/uievents/#event-type-DOMFocusOut)
* [MouseEvent](https://w3c.github.io/uievents/#idl-mouseevent) events, including [auxclick](https://w3c.github.io/uievents/#event-type-auxclick), [click](https://w3c.github.io/uievents/#event-type-click), [dblclick](https://w3c.github.io/uievents/#event-type-dblclick), [mousedown](https://w3c.github.io/uievents/#event-type-mousedown), [mouseup](https://w3c.github.io/uievents/#event-type-mouseup), [mouseenter](https://w3c.github.io/uievents/#event-type-mouseenter), [mouseleave](https://w3c.github.io/uievents/#event-type-mouseleave), [mousemove](https://w3c.github.io/uievents/#event-type-mousemove), [mouseout](https://w3c.github.io/uievents/#event-type-mouseout), [mouseover](https://w3c.github.io/uievents/#event-type-mouseover), and [wheel](https://w3c.github.io/uievents/#event-type-wheel)

HTML does the same:
* [DragEvent](https://html.spec.whatwg.org/multipage/dnd.html#the-dragevent-interface): dragstart, drag, dragenter, dragexit, dragleave, dragover, drop, and dragend

It actually goes a bit farther, and as far as I can tell, there is no event in any spec (I have checked DOM, UI-Events, HTML, CSSOM-View, css-transitions, css-animations, ServiceWorkers, Fetch, and Input Events) that has an additional attribute of type EventTarget called anything other than `relatedTarget`.

So yeah, I sympathize that this is not a terribly descriptive name, but it does seem to be the conventional way to handle this kind of information.

**Comment by hugoholgersson** [comment]
Right ok. I didn't know `relatedTarget` was used that extensively already.

**Comment by frivoal** [comment]
Neither did I :) I had seen it here and there, but I had not checked whether it was universal. Looks like it is.
