### ISSUE TITLE
iframes: focusable vs scrollable

### ISSUE THREAD

**Issue by frivoal** [WICG/spatial-navigation#43]
For the current processing model to work correctly we need the thing that is focusable and the thing that is scrollable in an iframe to be the same thing. If the parenting relationship ends up wrong, the algorithm may do the wrong things. Between the host element, the document, the document element, the viewport, etc, it's non obvious.

We need to check it is defined correctly.

**Comment by jihyerish** [comment]
I think the iframe would be both focusable and scrollable. 

If the focus moves inside the iframe element, the document of iframe gains focus and it starts to find the best candidate for the document.
Also, if the focus moves outside of the iframe, the parent window of iframe gains focus.

So, basically, scrollable iframe works similar to the scroll container.
You can check the scroll container and iframe work the same via sample pages below:
- scroll container: https://wicg.github.io/spatial-navigation/sample/heuristic_scrollable.html
- iframe : https://wicg.github.io/spatial-navigation/sample/heuristic_iframe.html

**Comment by frivoal** [comment]
From a behavior point of view, I think there is not really a big question here. What I meant was when a element inside the iframe has focus, what is the spatnav container? the iframe element itself, or the document? which one is scrollable? I just want to review both our spec and the html spec about focusability to make sure that there's no contradiction.

**Comment by jihyerish** [comment]
> when a element inside the iframe has focus, what is the spatnav container?

In this case, I think the document of the iframe element should be the spatnav container.

The iframe element is scrollable, but the document of it is scrollable.
Since HTML5, `scrolling` attribute on the iframe element had been deprecated.
(Reference: https://html.spec.whatwg.org/multipage/obsolete.html#attr-iframe-scrolling)

Also, [in the spatnav spec, the spatnav containe](https://wicg.github.io/spatial-navigation/#spatial-navigation-focus-container)r is defined as "The viewport of a browsing context."
But the iframe isn't a browsing context, but it is a [browsing context container](https://html.spec.whatwg.org/multipage/browsers.html#browsing-context-container).

**Comment by frivoal** [comment]
Having reviewed the spec again, I believe it works as specified.

* In the general case, where the body of the document inside the iframe is overflow visible (either because it was in the first place, or because of [overflow propagation](https://drafts.csswg.org/css-overflow-3/#overflow-propagation)), we fall onto step 6 of section 7.2, which will get the right spatnav container, which will both be the scrollable thing and the focusable thing (i.e. the viewport/scrollport inside the iframe)

* In the rare case where the body element itself has scrollable overflow (can only happen if the root element also did), then it gets handled in step 5.2.else, and that seems correctly defined too.

Anyway, we can never be sure just by reading spec prose that there isn't a bug somewhere, but having reviewed it, I'm comfortable with what we say. Closing.
