### ISSUE TITLE
Add relevant commands to WebDriver

### ISSUE THREAD

**Issue by frivoal** [WICG/spatial-navigation#45]
[webDriver](https://w3c.github.io/webdriver/webdriver-spec.html) should be extended to be able to invoke spatnav (and sequential nav)

**Comment by hugoholgersson** [comment]
Maybe we could use [send_keys()](https://github.com/w3c/web-platform-tests/commit/8f93a78175a1c98e6d36bd8293ff5525edd0da91)? Maybe it's enough if tests send arrow-keys for spatnav and tab and shift+tab for seqnav. 

Sure, some users might use custom keys (or voice commands or something else) to trigger by spatnav, but spatnav's default triggers are the arrow keys, so that's what WPT should test for?

**Comment by junhoseo** [comment]
@frivoal , as far as I know, we can use testdriver.send_keys for initiating user input(https://github.com/w3c/web-platform-tests/pull/10113).
Do you think this is not sufficient?

**Comment by junhoseo** [comment]
> Maybe we could use send_keys()? Maybe it's enough if tests send arrow-keys for spatnav and tab and shift+tab for seqnav.

Oh, @hugoholgersson already comment same thing :)

**Comment by frivoal** [comment]
One specific implementation can decide that the arrow keys is how they trigger spatnav, and then they could use  [send_keys()](https://github.com/w3c/web-platform-tests/commit/8f93a78175a1c98e6d36bd8293ff5525edd0da91) to check that things behave as expected,  but this cannot be used for testing conformance with the specification itself, since the specification does **not** require that arrow keys is what triggers spatnav. It may be arrow keys, but it does not have to. So if a browser fails to do spatnav when you press an arrow key, that is not a spec violation, and we cannot make a conformance test fail for that.

See this comment for why we do not require the arrow keys specifically: https://github.com/WICG/spatial-navigation/issues/35#issuecomment-371702434

**Comment by hugoholgersson** [comment]
Good points.

I was just thinking, since seqnav hardcodes to tab and shift-tab, maybe spatnav could have hardcoded defaults too? Maybe explicit defaults would be appreciated by authors (and test writers and implementers)? 

Browser _extensions_ could capture and interpret other (voice etc) user commands and send arrow keys to the page. Then send_keys() could be used to test conformance but an imaginary QuakeBrowser would need to do the same thing to comply.

I can imagine using a scroll wheel to move focus sequentially. Someone might create an extension to do so. That extension would need to send tab keys to not break the web. For spatnav we have more freedom since the web does not (?) expect a behavior for the arrow keys. Still, I think we should try to align spatnav with seqnav as much as we can. I wonder how we best do that.

**Comment by frivoal** [comment]
seqnav does not hardcode to tab and shift tab. All modern desktop browsers do it, but the there's not requirement in the spec that it be so. Here's the relevant section in the HTML spec: https://html.spec.whatwg.org/multipage/interaction.html#sequential-focus-navigation

There's just a note in there that indicates that "typically" this is done with Tab and Shift tab, but that's it.

**Comment by frivoal** [comment]
I do think it is probably a good idea to push for spatnav to be "typicall" done with arrow keys (without shift), but for the reasons discussed in #35, I don't think this push should be done in the spec. This is a UX/UI debate, not a conformance debate.

**Comment by junhoseo** [comment]
Couldn't we use testdriver-vendor.js?
We may define our own arrow key event in testdriver.js, then its interpretation and initiating according key event can be done by testdriver-vendor.js.

**Comment by hugoholgersson** [comment]
I don't know much about WebDriver, but I guess WPT tests would do:

```
test_driver.snav('up').then(() => {
  assert_equals(document.activeElement, expectedElement);
});
```

Chrome's testdriver_vendor.js's translates the `snav('up')` to:
```
return test_driver.send_keys(document.activeElement, 'ArrowUp')
```
Here I called the function "**s**nav", not "spatnav", because it supports **s**eqnav's forward and backward alongside **s**patnav's up, down, left, right.

`test_driver.snav('forward')` translates to `test_driver.send_keys(document.activeElement, 'Tab')`.
