### ISSUE TITLE
Algorithm for finding navigation targets in a given direction needs clarification

### ISSUE THREAD

**Issue by cynthia** [WICG/spatial-navigation#8]
Remark about this part: https://github.com/WICG/spatial-navigation/blob/master/explainer.md#nav-rule-property-cssui4

The algorithm for determining how the implementation (or I guess, in this case a reference implementation polyfill) should find the next target in a given direction isn't specified - anything that is not obvious to implement (e.g. nearest) should be specified.

**Comment by jihyerish** [comment]
It needs to use more precise terms and find other corner cases, but the algorithm for finding the next targets can be: 

1. Set the range which contains the focusable element for the spatial navigation.
2. Find the 1st group of candidate target elements within the range depending on the direction of navigation as:
   i. If the up arrow key is pressed, all the elements with smaller calculated y position than the currently focused element are in the 1st group.
   ii. Otherwise, if the down arrow key is pressed, all the elements with greater calculated y position than the currently focused element are in the 1st group.
   iii. Otherwise, if the left arrow key is pressed, all the elements with smaller calculated x position than the currently focused element are in the 1st group.
   iv. Otherwise, if the right arrow key is pressed, all the elements with greater calculated x position than the currently focused element are in the 1st group.
3. If there isn't any element in the 1st group of candidate target elements, the focus moves following the heuristic spatial navigation algorithm.
4. Otherwise, get the navigation rule.
5. Find the 2nd group of candidate target elements within the range depending on the rule of navigation.
   i. If the rule is 'direction', the closest elements based on the shortest distance considering only one axis which is the direction of navigation from the currently focused element are in the 2nd group.
   ii. Otherwise, if the rule is 'projection', the first elements encountered when projecting the edge of the currently focused element are in the direction of navigation.
   iii. Otherwise, if the rule is 'nearest', the closest elements based on the shortest 2D distance from the currently focused element are in the 2nd group.
6. Find the topmost and leftmost element among the 2nd group of candidate target elements.
7. Let the topmost and leftmost element as a target element.
8. Move focus to the target element.

**Comment by jihyerish** [comment]
The algorithm about finding the next focusable element is described as [this](http://rawgit.com/wicg/spatial-navigation/first-draft/index.html#heuristics) in the earlier draft of spatial navigation.
This refers to the implementation in blink, but not exactly the same. 

I think this is simple version of the spatial navigation algorithm for implementing.
