### ISSUE TITLE
LG Pro:Centric compatibility

### ISSUE THREAD

**Issue by Sueloo** [WICG/spatial-navigation#88]
We have a problem to use this polyfill on a Pro:Centric device - it seems that it doesn't work at all. Is it compatible with this platform?

**Comment by anawhj** [comment]
Could you elaborate the environment of Pro:Centric device? (e.g. model, web engine version, app code)

Basically, the polyfill for spatial navigation works on most of browsers and devices with web app runtime. If you want to use the arrow key-based navigation in your web app, you can also refer to the spotlight library in the following link. http://enactjs.com/docs/modules/spotlight/

LG have a plan to align the enact framework with spatnav standards(polyfill) such an processing model and Web API so that end users can enjoy the convenient input method in several devices like Pro:Centric targeting hotel TV, beyond the browsers.

**Comment by jihyerish** [comment]
@Sueloo Thanks for reporting the issue!
Thanks to you, I've added the browser support status to the polyfill guideline.
(See: https://github.com/WICG/spatial-navigation/tree/master/polyfill#browser-support)

LG Pro:Centric device has dependancy on blink. 
I guess  the blink version lower than 45 had been shipped to the released device.
The polyfill works from the 49 version of the chrome browser.

Could you check which version of the blink in your Pro:Centric device?
Also, can you share how did you get to know the Pro:Centric device? 
I'm pleased and interested to hear that you used the polyfill on the device!

**Comment by jihyerish** [comment]
I think this issue depends on the version of the browser which is shipped in the device and the latest version of polyfill works well.
So I'm closing this issue.
