### ISSUE TITLE
What will this API find?

### ISSUE THREAD

**Issue by bkardell** [WICG/spatial-navigation#9]
What we discussed in our meetings and hallway conversations is that we'd start with a DOM-oriented API that allows us to 'find' an element - either the next/previous one in sequential order or spatially.  I'd like us to clarify what this should find, and why.  Here's why I think this really matters: We learn how to use things and when that changes it is disorienting and unfamiliar, this is why ARIA defines a number of interaction patterns like, for example, a set of tabs.  If you're a keyboard user (I am frequently) then you learn how tabs work.  When you see tabs, you know how you expect to interact with them.  It's no different for other kinds of users.  If I have a set of 4 tabs and focus is on the first tab, pressing tab again does not take me to the second tab, it enters the content of the active tab.  Changing the selected tab is done with keyboard directional keys.
A lot of current approaches to accessibility for things like this currently involve a concept which is referred to as "roving tab index" or "roaming tab index" (or something, we can't seem to keep that one entirely straight :))... In this example, all the tabs are tabindex="-1" - they are not in the natural sequential focus, but they are programmatically focusable. 

If I am on the first tab and I programmatically used our hypothetical API to find the next one, would we expect it to find the tabindex="-1" ones that are not hidden or only tabindex="0" ones ?

**Comment by frivoal** [comment]
How is it currently realized? Is this something you can get the browser to do for you based on some declarative construction of the tab set, or is this something authors have to code in js by themselves? In the later case, what we want to preserve is the interaction pattern, not necessarily the fact that it is currently coded using negative `tabindex` and some javascript (although we'll also need to make sure we don't break existing content, but that's sort of a separate question).

Alternatively, if this is something you can get the UA to do for you just based on declarative markup (what markup?), I think that  instead of being question about the API being discussed / proposed in #2, maybe this is rather something to be defined more generically in a (yet to be written) document that describes what the UA is expected to do when the arrow keys are pressed, which would include (but not be limited to) spatial navigation.

**Comment by robdodson** [comment]
> Is this something you can get the browser to do for you based on some declarative construction of the tab set, or is this something authors have to code in js by themselves?

Authors need to code it themselves. Typically listening for a keyup event and calling `focus()` on that next element. They may also update the `tabindex` on this newly focused element to be `tabindex=0` and set all of the siblings back to `tabindex=-1`. This way if the user tabs out of the control and hits shift-tab to return, their focus goes back to the previous item they interacted with.

> If I am on the first tab and I programmatically used our hypothetical API to find the next one, would we expect it to find the tabindex="-1" ones that are not hidden or only tabindex="0" ones ?

I imagine it would have to give you the `tabindex=-1` element. This _may_ allow us to simplify the way we currently do roving tabindex. Today's roving tabindex implementation is usually [a switch statement looking at every key that was pressed](https://github.com/GoogleChromeLabs/howto-components/blob/master/elements/howto-radio-group/howto-radio-group.js#L199-L238) and then moving focus based on that input. With spatnav you may be able to just collapse this into a single handler that just sets the old element to `tabindex=-1`, the new element to `tabindex=0`, and calls focus on the new element.

**Comment by bkardell** [comment]
@alice, @robdodson, @ianpouncey and I had some considerable conversation on this the last night of TPAC. We should prob work on writing up our collective thoughts from that convo

**Comment by robdodson** [comment]
@bkardell It sounded to me like you guys were discussing horizontal navigation, similar to scrolling maybe? It did occur to me that if I'm inside of a control that overflows horizontally or vertically that squatting on the up/down arrow keys might be really confusing for users because they then would lose the ability to scroll the container.

**Comment by bkardell** [comment]
@robdodson There's a separate issue about scrolling vs focus, I'm talking about very simply if there is a JavaScript API, how does it plug in... what does it find/not and what does that look like.  I think it would be good come to agreement on basic "shapes" of things before we talk about much else and since we talked about a lot in this area, again, I think we should collect those notes.

**Comment by frivoal** [comment]
I wonder if the newer things in CSS (grid, display: content) combined with spatial navigation could not get us there almost entirely without Javascript.

Open this in firefox (for support of grid + display:content) for instance: http://jsbin.com/covugom/edit?html,css,output

The only bit of javascript that's needed is to change which tab is the active one, and if there was spatial navigation, I think the interaction would be entirely as expected, without any need for roving tab index or similar trickery:
* focus a tab, then press shift: you move into the content of the tab (thanks to document order)
* focus a tab, then press right / left: you would move to the next / previous tab (thanks to spat-nav if you had it)

Now, sure, this is a toy example, so there's probably all sorts of way this breaks.

I think our default stance should be that spatnav should be just like sequential nav, and only focus things where tabindex isn't -1, unless we can find use cases which call for the opposite.

This example suggests to me is that the type of navigation you were suggesting can be achieved without ever needing tabindex=-1. Maybe there are other cases where it is still needed, but this specific example does seem to.

**Comment by robdodson** [comment]
> I think our default stance should be that spatnav should be just like sequential nav, and only focus things where tabindex isn't -1, unless we can find use cases which call for the opposite.

Based on the example you provided I think this could be a good first step. I would love to not have to do roving tabindex at all 😁 Maybe we go with this assumption and keep experimenting to make sure there are no gaps in it.

One important item to flag is that developers would need to be _very_ careful and make sure they don't ship components with several tabindex=0 elements to a browser which does not support spatnav. For example, a listbox could theoretically contain hundreds of items (think a country picker or something like that). If each of those items was tabindex=0, and the browser did not support spatnav, that component would become a kind of focus trap. A user would have to tab through every single item to advance. It's not a deal break, just something devs need to be aware of.

**Comment by robdodson** [comment]
Thinking about this a bit more... how would a developer prevent that listbox from becoming a focus trap if spatnav was following sequential nav?

**Comment by bkardell** [comment]
"focus a tab, then press shift" - @frivoal 

why press shift? you lost me a little right there?

**Comment by jihyerish** [comment]
> Thinking about this a bit more... how would a developer prevent that listbox from becoming a focus trap if spatnav was following sequential nav?

When I think about the listbox case, there are two situations when a single page uses both of the spatial navigation and sequential navigation, and the way to prevent the listbox becomes a focus trap for each case is:

1. The spatial navigation is enabled only for the listbox, not for the whole page.
   - Press tab to get out from the focus trap.
   - Press arrow keys to focus items in the listbox.

2. The spatial navigation is enabled for the whole page, but not for the listbox.
   - Press any arrow key to get out from the focus trap.
   - Press tab key to focus items in the listbox.

On top of that, there could be a situation(3) that the spatial navigation is enabled both for the whole page and the listbox.
In that case, if there is a vertically oriented listbox (which is scrollable only in vertical), the solution could be this way:
   - Press any arrow key to get out from the focus trap.
But up or down arrow key is hard to do it because before getting out of the listbox, the focus has to reach to the first item or the end item of the list.
   - Press up and down arrow keys to focus items in the listbox.

Considering all situations (1, 2, and 3), I think the best way to avoid a focus trap is 1.
Also, I found a nice sample which uses this approach  from [the samples in the wai-aria-practices](https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox.html)

**Comment by robdodson** [comment]
> The spatial navigation is enabled only for the listbox, not for the whole page.
> 
> Press tab to get out from the focus trap.
> Press arrow keys to focus items in the listbox.

OK, so once focus moves into a component that uses spatnav, the tab key no longer moves focus within that component. You can _only_ use the arrow keys.

> Also, I found a nice sample which uses this approach from the samples in the wai-aria-practices.

That example is interesting because instead of using roving tabindex, it just uses aria-activedescendant. Focus is always on the parent element and the up/down arrow keys just change which child is referenced by the aria-activedescendant attribute. I think often developers choose to either do roving tabindex _or_ aria-activedescendant, since they're two solutions for the same problem. You could rewrite that example using your proposed solution in 1.

**Comment by frivoal** [comment]
@bkardell Oops. That's just a very confusing typo. I meant "press tab", not "press shift". I'll fix the original comment, so that no one else needs to be confused. Hopefully it will make more sense now.

**Comment by frivoal** [comment]
@robdodson Actually, I wonder if the listbox and dropdow related examples are actually cases of spatnav or not. I'm leaning towards not.

I mean, for sure, you want the arrow keys to do the right thing in there, but I don't think that is sufficient. Most games will also handle arrow keys to do all sorts of things, like driving a car, and that's not spatnav.

In this case, as shown in the aria examples, there is no expectation (from screen readers and the like) that tab index be changed or that the actual browser focus be set on the items in the list. Instead, the whole state is handled using classes on the elements. In addition, selecting something is not just a matter of navigating the document, it changes state. If you submit a form, you don't tell the server which buttons were focused, but you do tell it which item(s) in the listbox were selected. Similarly, if the listbox itself loses focus, the element(s) inside it which was/were selected stay selected. You'll need the JS code anyway to handle the state changes (and to do something with that state).

So from a behavior point of view, this seems to be something other than focus. Call it selection if you like (although that too has a different meaning in another context, like selecting text).

From an implementation perspective, being able to tap into some "spatial" navigation logic wouldn't help much either. The list is a linear thing, there's no need for spatially aware browser logic to help you find the next item.

In contrast, the tabset example was indeed about moving focus.

What we do need to define is the interaction between key event handlers and spatial navigation, so that if a user goes onto https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox.html and spatnavs their way around, what happens is predictable and controllable. The answer to that question seems relatively simple: when an arrow key is pressed, the KeyboardEvent fires first. If preventDefault is called, spatnav is cancelled. If you open that page in presto based opera, that's what you get, and that's very usable.

**Comment by robdodson** [comment]
> In this case, as shown in the aria examples, there is no expectation (from screen readers and the like) that tab index be changed or that the actual browser focus be set on the items in the list.

I'm not sure if that's entirely true. I've seen the ARIA Authoring Practices present both roving tabindex and aria-activedescendant as two solutions for the same problem. For instance, their radio group examples illustrate how to do both:

- [radio group with roving tabindex](https://www.w3.org/TR/wai-aria-practices/examples/radio/radio-1/radio-1.html)
- [radio group with aria-activedescendant](https://www.w3.org/TR/wai-aria-practices/examples/radio/radio-2/radio-2.html)

I don't know which technique is more common on the web, though, I think it may be roving tabindex just because it's been supported longer than aria-activedescendant. This may not have a ton of bearing on this conversation but I wanted to make the information available :)

> Instead, the whole state is handled using classes on the elements. In addition, selecting something is not just a matter of navigating the document, it changes state. If you submit a form, you don't tell the server which buttons were focused, but you do tell it which item(s) in the listbox were selected. Similarly, if the listbox itself loses focus, the element(s) inside it which was/were selected stay selected. You'll need the JS code anyway to handle the state changes (and to do something with that state).

Yep that's true. My hope is/was that I could use spatnav to eliminate some of that code. For instance, I could stop listening for specific keyboard events and looking up the next or previous focusable element. Instead I could have a spatnav handler that told me which element the user was trying to focus. Then I just remove the active class from the previously focused element and add it to the new one.

But I realize that's different from what we're discussing here 😁 

If I recall, the current proposal is for an API where I tell spatnav a direction and it tells me the nearest focusable element. Which would mean I'd still need to listen for keyboard events.

> The answer to that question seems relatively simple: when an arrow key is pressed, the KeyboardEvent fires first. If preventDefault is called, spatnav is cancelled.

Maybe I'm wrong, but this sounds a bit different from the API @bkardell was discussing. Based on his [initial comment](https://github.com/WICG/spatial-navigation/issues/9#issue-273006241), it sounded like he was describing a JavaScript API, like

```js
let nextFocusableElement = getFocusableElement(direction)
```

I think maybe you're describing how someone would prevent focus from moving if they were using the `spatnav` CSS properties. Sorry if I'm confusing things 😛

**Comment by frivoal** [comment]
This discussion raises a number of interesting points, but it predates the spec in its current form. By and large, I think the points raised are addressed by the spec as it is today, and even if not, this thread is too broad to be directly actionable.

I am closing this issue, but this is not meant to shutdown any suggestion made in this thread that you believe has not been addressed yet. Individual specific issues welcome.
